const os=require("os")
console.log(os.arch())
console.log(os.cpus())
console.log(os.freemem())
console.log(os.release())
console.log(os.totalmem())
console.log(os.uptime())
console.log(os.type())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.networkInterfaces())